### ISSUE TITLE
Make it possible to download DVC artifact

### ISSUE THREAD

**Issue by aguschin** [iterative/gto-action#17]
Suggested usage:
```
steps:
  - uses: actions/checkout@v3
  - id: gto
    uses: iterative/gto-action@v1
    with:
       download: true
```

Given a Git tag, action will figure out artifact `name` and path to dvc.yaml, and will call `dvc get . {path/to/dvc.yaml}:{name} -o name`.

Questions:
1. Should it be `-o path/to/artifact` instead?

2. How to allow to set a special path to download it to?
```
steps:
  - id: gto
    uses: iterative/gto-action@v1
    with:
       download: path-to-set  # Won't it be ambiguous?
```

3. How to allow to pass ENV vars to auth with DVC? I guess it should work simply with `env:` specification. E.g. how we do in [example-gto](https://github.com/iterative/example-gto/blob/mlem/.github/workflows/deploy-model-with-mlem.yml)
```
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
```
