### ISSUE TITLE
`gto-action` to register version or assign stage

### ISSUE THREAD

**Issue by aguschin** [iterative/gto-action#42]
1. > Btw, I see you're trying to assign a stage with GTO in CI/CD. Would you use `gto-action` if it could do that for you? Like
```
steps:
  - uses: actions/checkout@v3
  - uses: iterative/gto-action@v2
    with:
      artifact: mymodel
      assign: dev
```

From https://discord.com/channels/485586884165107732/903647230655881226/1143566404679897098

2. In the same discussion, the use case mentioned requires to assign stages to many models. How to do that in this GH action?
